#!/usr/bin/env python3
import os
import json
from pathlib import Path

XDG_STATE_HOME = os.environ.get("XDG_STATE_HOME", str(Path.home() / ".local" / "state"))
XDG_CONFIG_HOME = os.environ.get("XDG_CONFIG_HOME", str(Path.home() / ".config"))
SCSS_FILE = Path(XDG_STATE_HOME) / "quickshell" / "user" / "generated" / "material_colors.scss"
HEROIC_THEMES_ROOT = Path(XDG_CONFIG_HOME) / "heroic" 
THEME_NAME = "themes"
HEROIC_THEME_DIR = HEROIC_THEMES_ROOT / THEME_NAME
HEROIC_THEME_FILE = HEROIC_THEME_DIR / f"{THEME_NAME}.css"
HEROIC_JSON_FILE = HEROIC_THEME_DIR / f"{THEME_NAME}.json"

def get_colors():
    colors = {}
    if not SCSS_FILE.exists():
        return colors
    with open(SCSS_FILE, 'r') as f:
        for line in f:
            if line.startswith('$'):
                line = line.strip()
                if ':' in line:
                    name, val = line.split(':', 1)
                    colors[name.strip('$').strip()] = val.strip().strip(';')
    return colors

def main():
    colors = get_colors()
    if not colors:
        print("No colors found in SCSS file.")
        return

    # Color definitions with fallbacks
    bg = colors.get('background', '#131316')
    surface = colors.get('surface', '#131316')
    on_surface = colors.get('onSurface', '#E5E1E5')
    on_surface_variant = colors.get('onSurfaceVariant', '#C8C5CF')
    
    primary = colors.get('primary', '#C4C2ED')
    on_primary = colors.get('onPrimary', '#2D2D4F')
    primary_container = colors.get('primaryContainer', '#2A2A4C')
    
    error = colors.get('error', '#FFB4AB')
    error_container = colors.get('errorContainer', '#93000A')
    
    success = colors.get('success', '#B5CCBA')
    success_container = colors.get('successContainer', '#374B3E')
    
    outline = colors.get('outline', '#928F98')
    outline_variant = colors.get('outlineVariant', '#47464E')
    
    surface_low = colors.get('surfaceContainerLow', '#1C1B1E')
    surface_container = colors.get('surfaceContainer', '#201F22')
    surface_high = colors.get('surfaceContainerHigh', '#2A292C')
    surface_bright = colors.get('surfaceBright', '#3A393C')

    heroic_css = f"""
/* Generated by Quickshell - Dynamic Material Theme */
body.{THEME_NAME} {{
  --background: {bg};
  --background-darker: {surface_low};
  --background-secondary: {surface_container};
  --background-lighter: {surface_high};
  --accent: {primary};
  --accent-overlay: {on_primary};

  --navbar-background: {surface_low};
  --body-background: {bg};
  --current-background: {bg};
  --text-default: {on_surface};
  --text-secondary: {on_surface_variant};
  --text-tertiary: {outline};
  --navbar-accent: {on_surface_variant};
  --navbar-active: {primary};
  --navbar-active-background: {surface_container};
  --success: {success};
  --success-hover: {success_container};
  --input-background: {surface_container};
  --modal-background: {surface};
  --modal-border: {outline_variant};
  --primary: {primary};
  --primary-hover: {primary_container};
  --danger: {error};
  --danger-hover: {error_container};
  --anticheat-denied: var(--danger);
  --anticheat-broken: {colors.get('term3', '#FFDDEC')};
  --anticheat-running: var(--text-default);
  --anticheat-supported: {success};
  --anticheat-planned: {colors.get('tertiary', '#D7C689')};
  --text-title: {primary};
  --icons-background: {surface_high};
  --action-icon: {on_surface_variant};
  --action-icon-hover: {on_surface};
  --action-icon-active: {primary};
  --icon-disabled: {outline};
  --cancel-button: {error};
  --neutral-06: {on_surface};
  
  /* Additional UI variables */
  --divider: {outline_variant};
  --gradient-body-background: {bg};
  --download-button: {primary_container};
  --download-button-overlay: {primary};
}}

/* MUI specific overrides for better integration */
body.{THEME_NAME} .MuiPaper-root {{
    background-color: var(--background-secondary) !important;
}}

body.{THEME_NAME} .MuiButton-containedPrimary {{
    background-color: var(--primary) !important;
    color: {on_primary} !important;
}}

body.{THEME_NAME} .MuiButton-outlinedPrimary {{
    border-color: var(--primary) !important;
    color: var(--primary) !important;
}}

body.{THEME_NAME} .MuiTypography-root {{
    color: var(--text-default) !important;
}}

body.{THEME_NAME} .MuiSvgIcon-root {{
    color: var(--action-icon) !important;
}}

body.{THEME_NAME} .MuiListItem-root.Mui-selected {{
    background-color: var(--navbar-active-background) !important;
    color: var(--navbar-active) !important;
}}

/* Scrollbars */
body.{THEME_NAME} ::-webkit-scrollbar {{
    width: 8px;
    height: 8px;
}}

body.{THEME_NAME} ::-webkit-scrollbar-track {{
    background: var(--background);
}}

body.{THEME_NAME} ::-webkit-scrollbar-thumb {{
    background: var(--background-lighter);
    border-radius: 4px;
}}

body.{THEME_NAME} ::-webkit-scrollbar-thumb:hover {{
    background: var(--accent);
}}
"""

    heroic_json = {
        "name": "Generated Theme",
        "filename": f"{THEME_NAME}.css",
        "author": "Quickshell"
    }

    HEROIC_THEME_DIR.mkdir(parents=True, exist_ok=True)
    with open(HEROIC_THEME_FILE, 'w') as f:
        f.write(heroic_css)
    
    with open(HEROIC_JSON_FILE, 'w') as f:
        json.dump(heroic_json, f, indent=2)
    

if __name__ == "__main__":
    main()
